### ISSUE TITLE
cause leak

### ISSUE THREAD

**Issue by xingag** [tianzhijiexian/UIBlock#1]
It cause leak,please see the Screen shots

https://github.com/hush881025/pics/blob/master/pics/one.jpg

**Comment by kaleai** [comment]
感谢你用了强大的leak检查工具，这个溢出我也遇到过。我分析是因为这个界面中有editText，内部的文字和剪切板有引用，但退出后剪切板仍旧有文字的引用，从而出现溢出。从报出的信息来看，没有定位到我的代码中，所以我怀疑是一个系统的溢出。我很想听听你的建议。

**Comment by xingag** [comment]
确实是edittext导致的泄露；刚才试了把复制粘贴静止以后，貌似没有出现过了

**Comment by kaleai** [comment]
那么这个可以理解为系统层级的溢出。你可以上报下谷歌看看，这样的问题貌似还挺多的。

**Comment by xingag** [comment]
好的
