### ISSUE TITLE
关于ContainUIBlockActivity接口

### ISSUE THREAD

**Issue by zeng1990java** [tianzhijiexian/UIBlock#2]
ContainUIBlockActivity接口中除了getUIBlockManager外的三个方法好像没有存在的必要性

**Comment by kaleai** [comment]
我承认这个接口的意义不大，但我这么做的原因如下：
必须要求使用者去在activity的回调中调用UIBlock的对应方法，为了避免使用者的疏忽，用这种方式进行提示。
其次，如果以后版本增加了一些回调，我可以改这个接口，这样使用者就知道新版本增加了哪些回调。

听说ios的hook很简单，但android中没找到什么好办法去hook进activity的生命周期方法。
