### ISSUE TITLE
UIBlock里能使用butterknife吗？

### ISSUE THREAD

**Issue by fflamingogo** [tianzhijiexian/UIBlock#4]

**Comment by kaleai** [comment]
理论上没啥问题，你给他注入时传入一个rootView就行。

**Comment by kaleai** [comment]
感觉它这个注入器写的挺好的，你可以去尝试一下。如果不能用我就去改我的项目。我这里能用databinding，所以用它也没问题

**Comment by fflamingogo** [comment]
@tianzhijiexian 我在bindViews上加了ButterKnife.bind(getActivity())或加ButterKnife.bind(getRootView())，控件都报了空指针了

**Comment by kaleai** [comment]
用ButterKnife.bind(getRootView())的代码是怎样的呢？贴一下

**Comment by kaleai** [comment]
你首先看看getRootView()是否为null，如果不是null再看是不是绑定出错。activity中add了这个UIBlock了么

**Comment by fflamingogo** [comment]
```
     @Bind(R.id.recyclerview)
UltimateRecyclerView ultimateRecyclerView;

@Override
protected void bindViews() {
    if (getRootView() != null) {
        ButterKnife.bind(getRootView());
    } else {
        T.showShort("err");
    }

    //        ultimateRecyclerView = getView(R.id.recyclerview);
}
```

我如果自己getview的话是没问题的

**Comment by fflamingogo** [comment]
@tianzhijiexian 顺便问问，UIBlock能在fragment里用吗？adapter里呢

**Comment by kaleai** [comment]
从UIblock的设计上来说就是为了替代fragment用的，自然不是放在fragment中的。而且fragment中套这个，复杂度太大了。adapter中的item么？item怎么接收activity的回调是个问题，adapter中的item得到activity也不合适。adapter的item用我的commonAdapter项目即可。
这个注入框架看来有点问题，我研究下看看。可以把你依赖的注入框架的gradle配置语句给我一下么。我调试一下

**Comment by kaleai** [comment]
我明白了，是你的调用方法有问题：ButterKnife.bind(this,getRootView()); 试试这个

**Comment by fflamingogo** [comment]
哈哈，确实可以了，厉害。现在的app一进首页就有几个tab，这就要用到fragment+viewpager，这个用view来替代合适吗？adapter的那个我再研究下

**Comment by kaleai** [comment]
现在已经支持了，请参考最新的demo。谢谢你的使用

**Comment by fflamingogo** [comment]
厉害，我学习学习

**Comment by kaleai** [comment]
如果已经确认了支持，你可以关闭这个issue了。谢谢了

**Comment by famik** [comment]
请问需不需要unbind的？

**Comment by kaleai** [comment]
@gfm688 需要
