### ISSUE TITLE
如果没有add过block，在onDestory的时候会报空指针异常

### ISSUE THREAD

**Issue by Lincoln-cn** [tianzhijiexian/UIBlock#5]
查看源码之后发现，只有调用了add方法，才会创建Block的List，如果没有add过，在调用onDestory的时候Block的List调用clean方法，就会因为List是空对象报错。

**Comment by kaleai** [comment]
这里是我的失误，很抱歉。我去查源码，然后修复掉

**Comment by kaleai** [comment]
已经修复了，但没有升级gradle的版本。如果你急用的话，我就去升级一下

**Comment by Lincoln-cn** [comment]
感谢你的修复。
