### ISSUE TITLE
怎样替换掉另一个block？

### ISSUE THREAD

**Issue by wenboLee** [tianzhijiexian/UIBlock#7]
跟Fragment一样，我需要替换掉Fragment，但是UiBlock似乎做不到啊，manage的remove方法用了没有效果的，楼主怎么看 @tianzhijiexian

**Comment by kaleai** [comment]
uiblock是掌管逻辑的，要替换是要对view进行处理然后再做uiblock的绑定。其实uiblock当初的设计并不支持回退栈和替换操作的，仅仅是用来解耦的。
